server:
  port: 8500
  servlet:
    context-path: /faq
spring:
  #mysql连接
  datasource:
    url: jdbc:mysql://122.112.242.241:3306/fqa_pair?characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: lca
    password: lerry_lca.MySQL
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    throw-exception-if-no-handler-found: true
  #redis连接
  redis:
    host: 122.112.242.241
    port: 6379
    database: 6
    jedis:
      pool:
        max-active: 50
        min-idle: 20
    password: lerry_lca.Redis
  #引入自定义配置，application-user.yml
  profiles:
    include:
      - user

#es连接
elasticsearch:
  #节点1(若有集群，可往后追加，并修改配置类ElasticsearchConfig.java)
  node-1:
    host: localhost
    port: 9200